name: Prettier
on:
    pull_request:
        types: [opened, synchronize, edited, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm install
            - run: npm run format-check
