name: CI jobs

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn install --frozen-lockfile 
          yarn test

  Eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run ESlint
        run: yarn lint
