name: CI jobs

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          yarn install --frozen-lockfile 
          yarn test

  Eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run ESlint
        run: yarn lint

  # Storybook:
  #   name: Test Storybook
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile
  #     - name: Install Playwright
  #       run: npx playwright install --with-deps
  #     - name: Build Storybook
  #       run: yarn storybook:build --quiet
  #     - name: Serve Storybook and run tests
  #       run: |
  #         npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
  #           "npx http-server storybook-static --port 6006 --silent" \
  #           "npx wait-on tcp:6006 && yarn storybook:test"
