name: Deploy to Preview Channel

on:
    pull_request:

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        env:
            REACT_APP_FIREBASE_API_KEY: ${{secrets.REACT_APP_FIREBASE_API_KEY}}
            REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
            REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
            REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
            REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
            REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID}}
            REACT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.REACT_APP_FIREBASE_MEASUREMENT_ID}}
            REACT_APP_REGEX_PASSWORD: ${{secrets.REACT_APP_REGEX_PASSWORD}}
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
            with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                expires: 30d
                projectId: saikai-production
            env:
                CI: true
