name: Deploy to Preview Channel

on:
    pull_request:

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run build
            - uses: w9jds/firebase-action@master
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
                  expires: 30d
                  projectId: saikai-production
              env:
                  CI: true
